# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 891, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label.setObjectName("label")
        self.hostname = QtWidgets.QLineEdit(self.frame)
        self.hostname.setGeometry(QtCore.QRect(90, 10, 141, 25))
        self.hostname.setText("")
        self.hostname.setObjectName("hostname")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 81, 17))
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(330, 10, 113, 25))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(450, 10, 71, 17))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(520, 10, 111, 25))
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(640, 10, 41, 17))
        self.label_4.setObjectName("label_4")
        self.port = QtWidgets.QLineEdit(self.frame)
        self.port.setGeometry(QtCore.QRect(690, 10, 81, 25))
        self.port.setObjectName("port")
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(790, 10, 89, 25))
        self.loginButton.setAutoFillBackground(False)
        self.loginButton.setStyleSheet("background-color: rgb(114, 159, 207);\n"
"color: rgb(0, 0, 0);\n"
"font: 57 11pt \"Ubuntu\";")
        self.loginButton.setObjectName("loginButton")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(80, 460, 671, 31))
        self.status.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.status.setObjectName("status")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 460, 71, 31))
        self.label_9.setStyleSheet("font: 13pt \"Ubuntu\";\n"
"color: rgb(204, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(790, 460, 89, 25))
        self.logoutButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.logoutButton.setObjectName("logoutButton")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 80, 891, 371))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.retrButton = QtWidgets.QPushButton(self.frame_2)
        self.retrButton.setGeometry(QtCore.QRect(20, 0, 89, 25))
        self.retrButton.setObjectName("retrButton")
        self.deleButton = QtWidgets.QPushButton(self.frame_2)
        self.deleButton.setGeometry(QtCore.QRect(20, 230, 89, 25))
        self.deleButton.setObjectName("deleButton")
        self.storButton = QtWidgets.QPushButton(self.frame_2)
        self.storButton.setGeometry(QtCore.QRect(20, 30, 89, 25))
        self.storButton.setObjectName("storButton")
        self.mkdirButton = QtWidgets.QPushButton(self.frame_2)
        self.mkdirButton.setGeometry(QtCore.QRect(20, 70, 89, 25))
        self.mkdirButton.setObjectName("mkdirButton")
        self.listButton = QtWidgets.QPushButton(self.frame_2)
        self.listButton.setGeometry(QtCore.QRect(20, 110, 89, 25))
        self.listButton.setObjectName("listButton")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 270, 89, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pwdButton = QtWidgets.QPushButton(self.frame_2)
        self.pwdButton.setGeometry(QtCore.QRect(20, 150, 89, 25))
        self.pwdButton.setObjectName("pwdButton")
        self.cwdButton = QtWidgets.QPushButton(self.frame_2)
        self.cwdButton.setGeometry(QtCore.QRect(20, 190, 89, 25))
        self.cwdButton.setObjectName("cwdButton")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(290, 20, 111, 17))
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(520, 40, 341, 311))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.remotedir = QtWidgets.QTableWidget(self.frame_4)
        self.remotedir.setGeometry(QtCore.QRect(20, 10, 311, 291))
        self.remotedir.setObjectName("remotedir")
        self.remotedir.setColumnCount(0)
        self.remotedir.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 67, 17))
        self.label_5.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setGeometry(QtCore.QRect(180, 40, 321, 311))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.localdir = QtWidgets.QTreeView(self.frame_3)
        self.localdir.setGeometry(QtCore.QRect(20, 10, 291, 291))
        self.localdir.setObjectName("localdir")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(650, 20, 131, 20))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 22))
        self.menubar.setObjectName("menubar")
        self.menuFTP_Client = QtWidgets.QMenu(self.menubar)
        self.menuFTP_Client.setObjectName("menuFTP_Client")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFTP_Client.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hostname:"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.status.setText(_translate("MainWindow", "File Successfully Transferred!"))
        self.label_9.setText(_translate("MainWindow", "Status:"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.retrButton.setText(_translate("MainWindow", "RETR"))
        self.deleButton.setText(_translate("MainWindow", "DELE"))
        self.storButton.setText(_translate("MainWindow", "STOR"))
        self.mkdirButton.setText(_translate("MainWindow", "MKDIR"))
        self.listButton.setText(_translate("MainWindow", "LIST"))
        self.pushButton_7.setText(_translate("MainWindow", "QUIT"))
        self.pwdButton.setText(_translate("MainWindow", "PWD"))
        self.cwdButton.setText(_translate("MainWindow", "CWD"))
        self.label_6.setText(_translate("MainWindow", "Local Directory"))
        self.label_5.setText(_translate("MainWindow", "Controls"))
        self.label_7.setText(_translate("MainWindow", "Remote Directory"))
        self.menuFTP_Client.setTitle(_translate("MainWindow", "FTP_Client"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
