# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1031, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label.setObjectName("label")
        self.hostname = QtWidgets.QLineEdit(self.frame)
        self.hostname.setGeometry(QtCore.QRect(90, 10, 141, 25))
        self.hostname.setText("")
        self.hostname.setObjectName("hostname")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(270, 10, 81, 17))
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(360, 10, 113, 25))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(500, 10, 71, 17))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(580, 10, 111, 25))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(720, 10, 41, 17))
        self.label_4.setObjectName("label_4")
        self.port = QtWidgets.QLineEdit(self.frame)
        self.port.setGeometry(QtCore.QRect(770, 10, 81, 25))
        self.port.setObjectName("port")
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(920, 10, 89, 25))
        self.loginButton.setAutoFillBackground(False)
        self.loginButton.setStyleSheet("background-color: rgb(114, 159, 207);\n"
"color: rgb(0, 0, 0);\n"
"font: 57 11pt \"Ubuntu\";")
        self.loginButton.setObjectName("loginButton")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(930, 550, 89, 25))
        self.logoutButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.logoutButton.setObjectName("logoutButton")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 80, 1031, 461))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 131, 411))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.remove = QtWidgets.QPushButton(self.frame_2)
        self.remove.setGeometry(QtCore.QRect(10, 100, 111, 25))
        self.remove.setStyleSheet("")
        self.remove.setObjectName("remove")
        self.noop = QtWidgets.QPushButton(self.frame_2)
        self.noop.setGeometry(QtCore.QRect(10, 140, 111, 25))
        self.noop.setStyleSheet("")
        self.noop.setObjectName("noop")
        self.pasv = QtWidgets.QPushButton(self.frame_2)
        self.pasv.setGeometry(QtCore.QRect(10, 220, 101, 25))
        self.pasv.setStyleSheet("")
        self.pasv.setObjectName("pasv")
        self.active = QtWidgets.QPushButton(self.frame_2)
        self.active.setGeometry(QtCore.QRect(10, 260, 101, 25))
        self.active.setStyleSheet("")
        self.active.setObjectName("active")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(20, 170, 81, 41))
        self.label_10.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.label_10.setObjectName("label_10")
        self.makeDir = QtWidgets.QPushButton(self.frame_2)
        self.makeDir.setGeometry(QtCore.QRect(10, 40, 111, 25))
        self.makeDir.setStyleSheet("")
        self.makeDir.setObjectName("makeDir")
        self.dirName = QtWidgets.QLineEdit(self.frame_2)
        self.dirName.setGeometry(QtCore.QRect(10, 10, 113, 25))
        self.dirName.setObjectName("dirName")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(290, 20, 111, 17))
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(550, 40, 461, 411))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.remotedir = QtWidgets.QTableWidget(self.frame_4)
        self.remotedir.setGeometry(QtCore.QRect(20, 20, 421, 351))
        self.remotedir.setObjectName("remotedir")
        self.remotedir.setColumnCount(0)
        self.remotedir.setRowCount(0)
        self.homedir = QtWidgets.QPushButton(self.frame_4)
        self.homedir.setGeometry(QtCore.QRect(20, 380, 89, 25))
        self.homedir.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.homedir.setObjectName("homedir")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 67, 17))
        self.label_5.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setGeometry(QtCore.QRect(160, 40, 371, 411))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.localdir = QtWidgets.QTreeView(self.frame_3)
        self.localdir.setGeometry(QtCore.QRect(20, 20, 331, 351))
        self.localdir.setObjectName("localdir")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(650, 20, 131, 20))
        self.label_7.setObjectName("label_7")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(10, 579, 1031, 241))
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.status = QtWidgets.QLabel(self.frame_6)
        self.status.setGeometry(QtCore.QRect(100, 10, 671, 31))
        self.status.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.status.setObjectName("status")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 71, 31))
        self.label_9.setStyleSheet("font: 13pt \"Ubuntu\";\n"
"color: rgb(204, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.statusWindow = QtWidgets.QTableWidget(self.frame_6)
        self.statusWindow.setGeometry(QtCore.QRect(30, 40, 841, 181))
        self.statusWindow.setObjectName("statusWindow")
        self.statusWindow.setColumnCount(0)
        self.statusWindow.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 22))
        self.menubar.setObjectName("menubar")
        self.menuFTP_Client = QtWidgets.QMenu(self.menubar)
        self.menuFTP_Client.setObjectName("menuFTP_Client")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFTP_Client.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hostname:"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.remove.setText(_translate("MainWindow", "REMOVE DIR"))
        self.noop.setText(_translate("MainWindow", "CHECK CONN."))
        self.pasv.setText(_translate("MainWindow", "PASSIVE"))
        self.active.setText(_translate("MainWindow", "ACTIVE"))
        self.label_10.setText(_translate("MainWindow", "Conn Type"))
        self.makeDir.setText(_translate("MainWindow", "MAKE DIR"))
        self.dirName.setPlaceholderText(_translate("MainWindow", "Dir Name"))
        self.label_6.setText(_translate("MainWindow", "Local Directory"))
        self.homedir.setText(_translate("MainWindow", "Home Dir"))
        self.label_5.setText(_translate("MainWindow", "Controls"))
        self.label_7.setText(_translate("MainWindow", "Remote Directory"))
        self.status.setText(_translate("MainWindow", "File Successfully Transferred!"))
        self.label_9.setText(_translate("MainWindow", "Status:"))
        self.menuFTP_Client.setTitle(_translate("MainWindow", "FTP_Client"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
